Extension { #name : #BlSpaceShortcutIds }

{ #category : #'*GToolkit-World' }
BlSpaceShortcutIds >> closeTabShortcutId [
	^ self shortcutIdForIdentifier: #SpaceCloseTab
]

{ #category : #'*GToolkit-World' }
BlSpaceShortcutIds >> closeWorldShortcutId [
	^ self shortcutIdForIdentifier: #SpaceCloseWorld
]

{ #category : #'*GToolkit-World' }
BlSpaceShortcutIds >> openGlobalMenuShortcutId [
	^ self shortcutIdForIdentifier: #SpaceOpenGlobalMenu
]

{ #category : #'*GToolkit-World' }
BlSpaceShortcutIds >> openPreviewerShortcutId [
	^ self shortcutIdForIdentifier: #SpaceOpenPreviewer
]

{ #category : #'*GToolkit-World' }
BlSpaceShortcutIds >> openSpotterShortcutId [
	^ self shortcutIdForIdentifier: #SpaceOpenSpotter
]

{ #category : #'*GToolkit-World' }
BlSpaceShortcutIds >> selectNextTabShortcutId [
	^ self shortcutIdForIdentifier: #SpaceSelectNextTab
]

{ #category : #'*GToolkit-World' }
BlSpaceShortcutIds >> selectPreviousTabShortcutId [
	^ self shortcutIdForIdentifier: #SpaceSelectPreviousTab
]
